version: 2
aliases:
- macos:
    xcode: 11.5.0
  working_directory: ~/project
  shell: /bin/bash --login -o pipefail
- run:
    name: Set Ruby Version
    command: echo "ruby-2.5.6" > ~/.ruby-version
- restore_cache:
    key: node-v1-{{ checksum "yarn.lock" }}-{{ arch }}
- run:
    name: Install node modules
    command: yarn
- save_cache:
    key: node-v1-{{ checksum "yarn.lock" }}-{{ arch }}
    paths:
    - node_modules
- restore_cache:
    key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
- run:
    command: bundle check || bundle install --path vendor/bundle
    working_directory: ios
- save_cache:
    key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
    paths:
    - ios/vendor/bundle
- run:
    name: Bundle iOS React Native Code and Assets
    command: node_modules/.bin/react-native bundle --entry-file='index.js' --bundle-output='./ios/MyDoh/main.jsbundle' --dev=false --platform='ios' --assets-dest='./ios' --sourcemap-output main.bundle.map
- run:
    name: Upload source map to sentry
    command: node_modules/@sentry/cli/bin/sentry-cli --auth-token $SENTRY_AUTH_TOKEN releases --org rbc-1c --project $SENTRY_PROJECT files $APP_ID-$VERSION upload-sourcemaps --dist $VERSION --rewrite main.bundle.map
- run:
    name: Push code to production
    command: appcenter codepush release-react -a ximxim/reactNativeDeployment -d Staging
code-push:
  macos:
    xcode: 11.5.0
  working_directory: ~/project
  shell: /bin/bash --login -o pipefail
  steps:
  - checkout
  - run:
      name: Set Ruby Version
      command: echo "ruby-2.5.6" > ~/.ruby-version
  - restore_cache:
      key: node-v1-{{ checksum "yarn.lock" }}-{{ arch }}
  - run:
      name: Install node modules
      command: yarn
  - save_cache:
      key: node-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      paths:
      - node_modules
  - restore_cache:
      key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
  - run:
      command: bundle check || bundle install --path vendor/bundle
      working_directory: ios
  - save_cache:
      key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
      paths:
      - ios/vendor/bundle
  - run:
      name: Push code to production
      command: appcenter codepush release-react -a ximxim/reactNativeDeployment -d Staging
jobs:
  code-push:
    macos:
      xcode: 11.5.0
    working_directory: ~/project
    shell: /bin/bash --login -o pipefail
    steps:
    - checkout
    - run:
        name: Set Ruby Version
        command: echo "ruby-2.5.6" > ~/.ruby-version
    - restore_cache:
        key: node-v1-{{ checksum "yarn.lock" }}-{{ arch }}
    - run:
        name: Install node modules
        command: yarn
    - save_cache:
        key: node-v1-{{ checksum "yarn.lock" }}-{{ arch }}
        paths:
        - node_modules
    - restore_cache:
        key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
    - run:
        command: bundle check || bundle install --path vendor/bundle
        working_directory: ios
    - save_cache:
        key: bundle-v1-{{ checksum "ios/Gemfile.lock" }}-{{ arch }}
        paths:
        - ios/vendor/bundle
    - run:
        name: Push code to production
        command: appcenter codepush release-react -a ximxim/reactNativeDeployment -d Staging
    environment:
    - APP_ID: org.reactjs.native.example.reactNativeDeployment
    - VERSION: 1.0.0
    - SENTRY_AUTH_TOKEN: 75b4d8dfd9b143d583df267c8100e6da646b0ba759944c7998e652e9c54006fa
    - SENTRY_PROJECT: reactNativeDeployment
    - CODE_PUSH_TOKEN: 57e10840322bb3f642622c6ca64ad0fb2599467d
    - CODE_PUSH_APP_NAME: ximxim/reactNativeDeployment
workflows:
  version: 2
  main:
    jobs:
    - code-push:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^\d+\.\d+\.\d+$/
